package com.mystikcoder.statussaver.utils

const val SESSION_ID = "session_id"
const val COOKIES = "cookies"
const val IS_INSTA_LOGGED_IN = "is_insta_logged_in"
const val CSRF = "csrf"
const val USER_ID = "user_id"
const val FB_COOKIES = "fb_cookies"
const val FB_KEY = "fb_key"
const val IS_FB_LOGGED_IN = "is_fb_logged_in"
const val WORK_URL = "work_url"
const val WORK_COOKIES = "cookies_work"
const val WORK_USER_AGENT = "user_agent_work"
const val WORK_PLATFORM_NAME = "platform_name"
const val WORKER_TAG = "instagram_downloader_worker"
const val WORKER_TAG_SHARECHAT = "shareChat_Worker_tag"
const val INSTAGRAM = "instagram"
const val FACEBOOK = "facebook"
const val ROPOSO = "roposo"
const val SHARE_CHAT = "share_chat"
const val MOJ = "mojapp"
const val MITRON = "mitron"
const val TWITTER = "twitter"
const val CHINGARI = "chingari"
const val LIKEE = "likee"
const val MX_TAKA_TAK = "mxtakatak"
const val JOSH = "myjosh"
const val TIKTOK = "tiktok"
const val WHATSAPP = "whatsapp"
const val WORKER_KEY_DOWNLOAD_URL = "download_url"
const val START_SERVICE = "start_service"
const val PAUSE_SERVICE = "pause_service"
const val WORKER_TAG_TWITTER = "worker-tag_twitter"
const val WORKER_TAG_TAKA_TAK = "mxTakaTakTag"
const val STOP_SERVICE = "STOP_SERVICE"
const val RESUME_SERVICE = "RESUME_SERVICE"
const val INSTAGRAM_USER_AGENT = "Instagram 9.5.2 (iPhone7,2; iPhone OS 9_3_3; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/420+"
const val INSTAGRAM_PARAMATERS = "?__a=1"
const val FACEBOOK_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
const val PRIVACY_POLICY_URL = "https://sites.google.com/view/mystikcoder/home"